[pytest]
# 测试文件匹配模式(即使不配置，pytest 也默认使用这些规则：)
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# 添加项目根目录到 sys.path（解决导入问题）
pythonpath = .

# 测试目录
testpaths = tests

# 命令行默认参数
addopts = 
    -v
    --tb=short
    --strict-markers
    #--disable-warnings

# 标记
markers =
    auth: 登录认证
    document: 文件处理  
    chat: 问答功能
    session: 会话管理
    smoke: 核心功能（从上面选几个最重要的）